#ifndef TESTPARAMS_H_
#define TESTPARAMS_H_

#define CLOCK_ID CLOCK_MONOTONIC
#define OSTIMER_TIMEOUT_SECONDS 0.001
#define OSTIMER_TIMEOUT_NANOSECONDS (OSTIMER_TIMEOUT_SECONDS*1000000000)
#define OSTIMER_TEST_RUNS 10000

#endif //TESTPARAMS_H_
